# frozen_string_literal: true

# Primary keys are UUIDv7, generated by Postgres 18's native uuidv7()
# (foundation plan_2). Time-ordered, so btree indexes stay dense — none of
# the random-UUID index bloat — and generation works for raw SQL and bulk
# inserts too, with no app-side callback.
#
# Note: UUIDv7 embeds the row's creation time. Fine for us — cue creation
# time is already visible in-app.
#
# - Generated migrations default to `id: :uuid` (generators config below).
# - Any `create_table` with a uuid primary key and no explicit :default gets
#   uuidv7() automatically (adapter prepend below), so hand-written
#   migrations can't forget it. Non-uuid tables (e.g. the Solid Queue/Cache
#   schemas, which keep bigint ids) are untouched.

Rails.application.config.generators do |g|
  g.orm :active_record, primary_key_type: :uuid
end

module Cue
  module UuidV7PrimaryKey
    def create_table(table_name, id: :primary_key, **options, &block)
      options[:default] = -> { "uuidv7()" } if id == :uuid && !options.key?(:default)
      super
    end
  end
end

ActiveSupport.on_load(:active_record_postgresqladapter) do
  prepend Cue::UuidV7PrimaryKey
end
